import pandas as pd

# サンプルデータを作成
data = {
    "MAL_ID": [1, 2, 3, 4, 5],  # アニメのID
    "Name": ["Naruto", "Bleach", "One Piece", "Attack on Titan", "Death Note"],  # アニメ名
    "sypnopsis": [
        "In a world of constant war between humans and witches, there exist the beastfallen—cursed humans born with the appearance and strength of an animal. Their physical prowess and bestial nature cause them to be feared and shunned by both humans and witches. As a result, many beastfallen become sellswords, making their living through hunting witches. Despite the enmity between the races, a lighthearted witch named Zero enlists a beastfallen whom she refers to as Mercenary to act as her protector. He travels with Zero and Albus, a young magician, on their search for the Grimoire of Zero: a powerful spell book that could be extremely dangerous in the wrong hands. During their journey, his inner kindness is revealed as he starts to show compassion and sympathy towards humans and witches alike, and the unlikely companions grow together.",
        "In times of need, if you look in the right place, you just may see a strange telephone number scrawled in red. If you call this number, you will hear a young man introduce himself as the Yato God. Yato is a minor deity and a self-proclaimed Delivery God, who dreams of having millions of worshippers. Without a single shrine dedicated to his name, however, his goals are far from being realized. He spends his days doing odd jobs for five yen apiece, until his weapon partner becomes fed up with her useless master and deserts him. Just as things seem to be looking grim for the god, his fortune changes when a middle school girl, Hiyori Iki, supposedly saves Yato from a car accident, taking the hit for him. Remarkably, she survives, but the event has caused her soul to become loose and hence able to leave her body. Hiyori demands that Yato return her to normal, but upon learning that he needs a new partner to do so, reluctantly agrees to help him find one. And with Hiyori's help, Yato's luck may finally be turning around.",
        "Gol D. Roger was known as the Pirate King, the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King. Enter Monkey D. Luffy, a 17-year-old boy who defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate ransacking villages for fun, Luffy's reason for being a pirate is one of pure wonder: the thought of an exciting adventure that leads him to intriguing people and ultimately, the promised treasure. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach the most coveted of all fortunes—One Piece.",
        "One day, Honey Kisaragi's a trendy, class-cutting Catholic schoolgirl. The next, her father's been murdered by demonic divas from a dastardly organization called Panther Claw. When his dying message reveals that she's an android, Honey uses the transformative power of the Atmospheric Element Solidifier - the very thing Panther Claw wanted to steal - to seek revenge against the shadowy clan. Can Honey fight her way up Panther Claw's ranks to defeat its leader, the sinister Sister Jill while managing to escape the watchful eyes of Miss Histler, her school's headmistress? Aided by journalist Hayami Seiji, his ninja father, and his lady-loving grade school brother, Honey sometimes appears as a racecar driver, sometimes as a glamorous model, and sometimes as a beggar, but her true identity is none other than the warrior of love, Cutie Honey!",
        "In the not so distant future, mankind has advanced to a state where complete body transplants from flesh to machine is possible. This allows for great increases in both physical and cybernetic prowess and blurring the lines between the two worlds. However, criminals can also make full use of such technology, leading to new and sometimes, very dangerous crimes. In response to such innovative new methods, the Japanese Government has established Section 9, an independently operating police unit which deals with such highly sensitive crimes. Led by Daisuke Aramaki and Motoko Kusanagi, Section 9 deals with such crimes over the entire social spectrum, usually with success. However, when faced with a new A level hacker nicknamed The Laughing Man, the team is thrown into a dangerous cat and mouse game, following the hacker's trail as it leaves its mark on Japan."
    ]  # あらすじ
}

# データフレームに変換
df = pd.DataFrame(data)

# CSVファイルとして保存
output_file = "anime.csv"
df.to_csv(output_file, index=False, encoding="utf-8")
print(f"CSV file '{output_file}' has been created successfully!")

# データフレームの確認
print(df)
